# Generated by Django 4.2.7 on 2023-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
