# Generated by Django 4.2.7 on 2023-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.collection'),
            preserve_default=False,
        ),
    ]
