# Generated by Django 4.2.7 on 2023-11-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.collection'),
        ),
    ]
